### ISSUE TITLE
script.openweathermap.maps can't download maps cause kodi slow closing.

### ISSUE THREAD

**Issue by NeverWise** [ronie/script.openweathermap.maps#1]
As I wrote in the title. I posted log file here http://xbmclogs.com/plmphtwsd.

**Comment by ronie** [comment]
can you check wich version of the script you have installed?
see /home/matteo/.kodi/addons/script.openweathermap.maps/addon.xml

**Comment by NeverWise** [comment]
Sure. The version is 0.0.10. Could be the location to create the problem?

**Comment by ronie** [comment]
could you please test something?

disable the tv shows next aired addon and restart kodi.
check if this makes a difference if you close kodi again now.

**Comment by NeverWise** [comment]
Now it works better but remain the problem of the map images not downloaded. Do you want see the log file?

**Comment by ronie** [comment]
nope that's a known issue.
the openweathermap severs are very slow and at times unreachable.
it's a problem at their end.https://openweathermap.desk.com/customer/portal/questions/14375594-weather-maps-slow-download
