### ISSUE TITLE
Changed api url format

### ISSUE THREAD

**Issue by TheUlpio** [ronie/script.openweathermap.maps#2]
I observed that with version 0.1.2 (and weather.openweathermap.extended 4.3.0) this addon was deactivated due to the fact that the site is unreacheable.
According to this
[https://openweathermap.org/api/weathermaps](url)
and inspecting the code, is easily to note that the url format in the addon is wrong, now openweathermap wants the api key for every query. I then adapted the code to add the api key picked from weather.openweathermaps.extended addon. 
For me it works really well, map fetching is fast (maybe i'm the only now that use this addon?) and reliable.
Ronie can you give it a glance?

Here my patches (with extra .txt extension... github...):
[script.openweathermap.maps.patch.txt](https://github.com/ronie/script.openweathermap.maps/files/917721/script.openweathermap.maps.patch.txt)
[weather.openweathermap.extended.patch.txt](https://github.com/ronie/script.openweathermap.maps/files/917722/weather.openweathermap.extended.patch.txt)

I'm not a programmer, but there is one thing might be useful to use this addon: everyone knows that weather forecasts are fetched both with a personal api key and a "universal" one. Enabling this addon should make mandatory using the personal api key, but i'm not able to implement this in python...

**Comment by ronie** [comment]
cheers, and sorry for the late reply!

i wasn't aware the api key was now mandatory, so a big thanx for the headsup!
your changes have been incorporated and updated versions of the addons have just been sent to the addon repo.
